//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEMO_DATA_BANKING.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_abe4fc_sampledbEntities : DbContext
    {
        public db_abe4fc_sampledbEntities()
            : base("name=db_abe4fc_sampledbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Association> Associations { get; set; }
        public virtual DbSet<Barangay> Barangays { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Miner> Miners { get; set; }
        public virtual DbSet<Municipality> Municipalities { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<Permit> Permits { get; set; }
        public virtual DbSet<Permit_Type> Permit_Type { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
    }
}
